DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS artist_count;
DROP TABLE IF EXISTS songs_count;
DROP TABLE IF EXISTS report;

CREATE TABLE IF NOT EXISTS songs(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	artist TEXT,
	title TEXT,
	year TEXT,
	url TEXT
);
CREATE TABLE IF NOT EXISTS artist_count(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	artist TEXT,
	occurence int
);
CREATE TABLE IF NOT EXISTS songs_count(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	title TEXT,
	occurence int
);
CREATE TABLE IF NOT EXISTS report(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	title TEXT,
	artist TEXT,
	url TEXT,
	duration int,
	occurence int
);